### ISSUE TITLE
Bughunting 7

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#79] opened 2019-02-05 04:35 UTC
![image](https://user-images.githubusercontent.com/3857155/52253345-f44be500-2939-11e9-8024-0c20522b4e78.png)
* Font-size and time for subtitle is incorrect
* Countdown and status not shown

**Comment by madvas** [comment] 2019-02-05 04:37
![image](https://user-images.githubusercontent.com/3857155/52253428-63293e00-293a-11e9-9c25-80f5343f6afb.png)
* Labels are not like they were before, they're flying too much in the air

**Comment by madvas** [comment] 2019-02-05 04:38
![image](https://user-images.githubusercontent.com/3857155/52253442-8358fd00-293a-11e9-87c6-c6e18b1728ec.png)
* Challenger address doesn't change cursor to pointer when hovered. Clicking works though

**Comment by madvas** [comment] 2019-02-05 04:41
![image](https://user-images.githubusercontent.com/3857155/52253509-d9c63b80-293a-11e9-91ea-d702fda8cfa0.png)
* Clicking on tx log entry doesn't do anything except closing tx log. It should take to `:related-href` as discussed in previous issue

**Comment by madvas** [comment] 2019-02-05 04:49
![image](https://user-images.githubusercontent.com/3857155/52253676-07f84b00-293c-11e9-9179-82da34131acc.png)
* Reveal My Vote is enabled even if I didn't vote at all

**Comment by madvas** [comment] 2019-02-05 05:22
![image](https://user-images.githubusercontent.com/3857155/52254502-a686ab00-2940-11e9-9064-1e9592d15cd6.png)
* Doesn't show "Your reward"

**Comment by madvas** [comment] 2019-02-05 05:32
![image](https://user-images.githubusercontent.com/3857155/52254796-1b0e1980-2942-11e9-9a68-8709eaa404d8.png)
I assume https://github.com/district0x/memefactory/issues/78#issuecomment-459619184 wasn't implemented yet

**Comment by madvas** [comment] 2019-02-05 05:36
![image](https://user-images.githubusercontent.com/3857155/52254878-9ff93300-2942-11e9-814e-48c84763d621.png)
* Typo -> claimed

**Comment by madvas** [comment] 2019-02-05 05:45
![image](https://user-images.githubusercontent.com/3857155/52255132-cc617f00-2943-11e9-8296-4bd05bbeb7cb.png)
* Make Seller address clickable, taking to Memefolio -> Selling

**Comment by madvas** [comment] 2019-02-05 05:56
![image](https://user-images.githubusercontent.com/3857155/52255512-637b0680-2945-11e9-8318-bb0a7d33fcb5.png)
* This is completely broken for me, had to uncheck grid-template-rows: 100%.

![image](https://user-images.githubusercontent.com/3857155/52255381-e94a8200-2944-11e9-9add-5a2cbae2ec4a.png)


As you can see, at the bottom it still stayed bit broken. I had to uncheck grid-template-rows: 50% 50% and it jumped down

![image](https://user-images.githubusercontent.com/3857155/52255458-3169a480-2945-11e9-92a5-68c068e60e6a.png)

**Comment by madvas** [comment] 2019-02-05 06:31
![image](https://user-images.githubusercontent.com/3857155/52256635-164d6380-294a-11e9-977a-0e8d2818b02e.png)
* Change text for no items for this section to: "No votes are running currently"

**Comment by madvas** [comment] 2019-02-05 06:35
![image](https://user-images.githubusercontent.com/3857155/52256824-d470ed00-294a-11e9-97d1-d60ee65aea1f.png)
* Create Offering doesn't work with empty Sales pitch, without any error message. It should be possible to create offering with empty sales pitch

**Comment by madvas** [comment] 2019-02-05 06:37
![image](https://user-images.githubusercontent.com/3857155/52256909-1ac64c00-294b-11e9-9bd1-560994cd0ca2.png)
* Ordering by cheapest doesn't work correctly

**Comment by madvas** [comment] 2019-02-05 06:39
![image](https://user-images.githubusercontent.com/3857155/52256953-4b0dea80-294b-11e9-927a-6a3bc18e1ba3.png)
* Ordering by Rarest also doesn't seem to work, it should order by least offered meme on marketplace. Which in this case is #9, so it should be on the first position

**Comment by madvas** [comment] 2019-02-05 06:42
![image](https://user-images.githubusercontent.com/3857155/52257041-a6d87380-294b-11e9-8e0e-c4c345a2cead.png)
When going to Creators leaderboard, it doesn't order By Earnings, which is default. Only after I select other ordering option, then select By Earnings back, it orders correctly

**Comment by madvas** [comment] 2019-02-05 06:45
![image](https://user-images.githubusercontent.com/3857155/52257177-40a02080-294c-11e9-8fdb-6fd53d01f2d6.png)
* By Single Card Sale ordering is incorrect

**Comment by madvas** [comment] 2019-02-05 06:46
![image](https://user-images.githubusercontent.com/3857155/52257223-7218ec00-294c-11e9-8cff-eae213838635.png)
* By Earnings ordering is incorrect

**Comment by madvas** [comment] 2019-02-05 06:50
![image](https://user-images.githubusercontent.com/3857155/52257289-d9cf3700-294c-11e9-91e2-ffb8337e7998.png)
* Clicking on area where Buy or Cancel button is after turning the card triggers transaction even when card is not turned.

**Comment by madvas** [comment] 2019-02-05 06:56
![image](https://user-images.githubusercontent.com/3857155/52257434-67128b80-294d-11e9-96e6-ed5d5c083a85.png)
![image](https://user-images.githubusercontent.com/3857155/52257446-71cd2080-294d-11e9-9f9c-23e4ae99abdc.png)
* Please make switching tabs to be same as switching different page. With different URLs, so browser back and forward functionality work for tabs as well

**Comment by jpmonettas** [comment] 2019-02-05 18:04
> ![image](https://user-images.githubusercontent.com/3857155/52256131-1ea49f00-2948-11e9-9c15-c7c474c9ea3f.png)
> 
> I'm gonna explain once more how I meant this: [#78 (comment)](https://github.com/district0x/memefactory/issues/78#issuecomment-459614831)
> 
> Currently you have 3 buttons:
> 
> * Vote Amount
> * Vote Reward
> * Challenge Reward
> 
> What we want is 3 buttons with following colors:
> 
> * Collect My Votes (purple)
> * Vote Reward (purple)
> * Challenge Reward (pink)
> 
> They all say "Collected" after collecting. Progressing state should say "Collecting..." for all 3 buttons.

We have currently 3 buttons with that behavior, since Vote Reward and Vote Amount are exclusive we are only showing one or the other. Should we show the three always?

**Comment by jpmonettas** [comment] 2019-02-05 18:06
> ![image](https://user-images.githubusercontent.com/3857155/52254544-d9c93a00-2940-11e9-9948-953c4ee23e79.png)
> 
> * Doesn't show chart and numbers, on both pages: meme detail and Resolved Challenges

This looks like votes where not revealed, that is why you have the claim amount option and no grahps or numbers

**Comment by jpmonettas** [comment] 2019-02-05 18:07
> ![image](https://user-images.githubusercontent.com/3857155/52254502-a686ab00-2940-11e9-9064-1e9592d15cd6.png)
> 
> * Doesn't show "Your reward"

Could not reproduce. It is showing Your reward in both screens for me.

**Comment by jpmonettas** [comment] 2019-02-05 18:41
> ![image](https://user-images.githubusercontent.com/3857155/52256953-4b0dea80-294b-11e9-927a-6a3bc18e1ba3.png)
> 
> * Ordering by Rarest also doesn't seem to work, it should order by least offered meme on marketplace. Which in this case is #9, so it should be on the first position

Current logic for this is order by meme/total-minted desc. Should I change to that?

**Comment by jpmonettas** [comment] 2019-02-06 13:15
> ![image](https://user-images.githubusercontent.com/3857155/52257434-67128b80-294d-11e9-96e6-ed5d5c083a85.png)
> ![image](https://user-images.githubusercontent.com/3857155/52257446-71cd2080-294d-11e9-9f9c-23e4ae99abdc.png)
> 
> * Please make switching tabs to be same as switching different page. With different URLs, so browser back and forward functionality work for tabs as well

@madvas are we sure we want to move browser history with SPA tabs? I don't think it makes a nice UX since when you hit back you probably want to move to previous "section" and not to start moving thru all the tabs you clicked in that section. Apps like gmail doesn't do that.

**Comment by jpmonettas** [comment] 2019-02-06 18:25
> ![image](https://user-images.githubusercontent.com/3857155/52256457-56601680-2949-11e9-9964-9081e1aa64ee.png)
> 
> * When going to meme detail page from marketplace, it doesn't load challenger rank and success rate

@madvas This is related to what I think is a bug in district-ui-graphql.

When two components ask for the same query but asks for different sub elements, for some reason the results doesn't get merged correctly.

meme-detail page does `meme` query and asks for  :challenge/challenger with 4 sub fields, while a subcomponent of it `buttons/reclaim-buttons` does the same `meme` query but only asks for `:user/address` inside `:challenge/challenger` and you end up with a challenger that has all 4 fields but `:user/address` nil
for some weird reason I haven't figured out yet, this doesn't go wrong when loading details page directly, only when you are coming from a different page thru navigate router event

**Comment by madvas** [comment] 2019-02-07 03:16
> > ![image](https://user-images.githubusercontent.com/3857155/52256131-1ea49f00-2948-11e9-9c15-c7c474c9ea3f.png)
> > I'm gonna explain once more how I meant this: [#78 (comment)](https://github.com/district0x/memefactory/issues/78#issuecomment-459614831)
> > Currently you have 3 buttons:
> > 
> > * Vote Amount
> > * Vote Reward
> > * Challenge Reward
> > 
> > What we want is 3 buttons with following colors:
> > 
> > * Collect My Votes (purple)
> > * Vote Reward (purple)
> > * Challenge Reward (pink)
> > 
> > They all say "Collected" after collecting. Progressing state should say "Collecting..." for all 3 buttons.
> 
> @madvas We have currently 3 buttons with that behavior, since Vote Reward and Vote Amount are exclusive we are only showing one or the other. Should we show the three always?

No, not show 3 at once. Keep showing as it is, just change text and color.

**Comment by madvas** [comment] 2019-02-07 03:17
> > ![image](https://user-images.githubusercontent.com/3857155/52254544-d9c93a00-2940-11e9-9948-953c4ee23e79.png)
> > 
> > * Doesn't show chart and numbers, on both pages: meme detail and Resolved Challenges
> 
> @madvas This looks like votes where not revealed, that is why you have the claim amount option and no grahps or numbers

I think some votes were revealed for this one, but not sure now, will try again

**Comment by madvas** [comment] 2019-02-07 03:18
> > ![image](https://user-images.githubusercontent.com/3857155/52256953-4b0dea80-294b-11e9-927a-6a3bc18e1ba3.png)
> > 
> > * Ordering by Rarest also doesn't seem to work, it should order by least offered meme on marketplace. Which in this case is #9, so it should be on the first position
> 
> Current logic for this is order by meme/total-minted desc. Should I change to that?

Ah I see, we can keep as it is

**Closed** 2019-02-08 07:58 UTC
