### ISSUE TITLE
Spinner imperfection

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#185] opened 2019-03-13 03:51 UTC
Spinner shows little bit weird behaviour. On Marketplace page, when switching ordering, the first second spinner is shown without "M" image and after half-second it jumps 10-15 pixels down and "M" starts to be visible. 
![spinner-bug](https://user-images.githubusercontent.com/3857155/54252433-68069080-457d-11e9-95ec-7e7810b20cfb.gif)

**Comment by jpmonettas** [comment] 2019-03-13 13:18
@madvas I couldn't reproduce this on my env, It looks like it is the time it takes for some browsers to show the image, so it shows the circle first and then the image.
Should this be MVP labeled?
The only solution I can imagine is to delay showing the spinner until img.onLoad finishes, but kind of implement a spinner for the spinner XD

I also think that this should be fixed whenever we review our assets cache headers, since currently it returns no-store and it is downloading that mouth image everytime.

**Comment by jpmonettas** [comment] 2019-03-13 14:28
This was fixed in QA by adding cache headers to our mouth asset.

**Closed by jpmonettas** 2019-03-13 14:28 UTC
Labels: MVP
