### ISSUE TITLE
Memefolio Created Tab Errors w/ more than 12 memes

### ISSUE THREAD

**Issue by joeyurgz** [district0x/memefactory#441] opened 2019-05-09 02:37 UTC
After adding a 13th meme, the created tab (https://beta.memefactory.io/memefolio/?tab=created) has a display issue when I scroll to the last of my memes. All cards shift one position once I get to the bottom so the 12th meme moves to where the 13th should be and the 13th is not shown.

**Comment by madvas** [comment] 2019-05-09 02:46
I confirm, I see the same issue, for the record this is memefolio's URL https://beta.memefactory.io/memefolio/0x5bca9df00a3b613c14b09664994de95f91ce77de?tab=created

**Comment by jpmonettas** [comment] 2019-05-09 13:38
I can't reproduce this now since there are 18 memes in that tab and works correctly for me. I tried locally with a 16 memes tab (so last row only have one) and it also works fine for me, so lets wait to see if this appears again.

**Comment by jpmonettas** [comment] 2019-05-09 13:46
Closing this now just to keep things cleaner, we can reopen if we see this again.

**Comment by madvas** [comment] 2019-05-09 13:48
It's still happening to me, but in the middle area, not at the end. You can see it's definitely shifting images for no reason. 
![scroll-shigting](https://user-images.githubusercontent.com/3857155/57458497-aa0d3380-729b-11e9-9e65-3ae8c3eae854.gif)

**Comment by jpmonettas** [comment] 2019-05-09 19:30
weird, I see a small jump but not missing anything:
![2019-05-09-16-28-48](https://user-images.githubusercontent.com/786299/57481096-ba131c00-7277-11e9-97eb-a65239f574b7.gif)

**Comment by Bradymck** [comment] 2019-05-14 23:12
I got this too today and think it's also causing issues with infinite scroll making the page go crazy on Windows (It's only doing what you see in above comments on Mac.) . It's preventing me from issuing memes that are at the bottom if on Windows.

**Comment by Bradymck** [comment] 2019-05-14 23:39
This is on MAC and with a single card at the end on my Meme Folio. However on windows, I don't see a single card at the end and infinite scroll spazzes out and won't let you issue cards. 

![ezgif-2-db8676395b12](https://user-images.githubusercontent.com/4667076/57738744-fbd40600-766d-11e9-8847-1b1df7dab544.gif)

**Comment by Bradymck** [comment] 2019-05-14 23:40
Windows version: 
![bugscrolling](https://user-images.githubusercontent.com/4667076/57739060-515ce280-766f-11e9-94ac-59b18a83a106.gif)

**Comment by Bradymck** [comment] 2019-05-14 23:40
It jumps around even worse than that if zoomed in.

**Closed** 2019-07-08 15:38 UTC
Labels: bug, can't reproduce
