### ISSUE TITLE
Faucet: Clicking on "Verification Code" label, won't trigger focused state

### ISSUE THREAD

**Issue by madvas** [district0x/memefactory#291] opened 2019-03-27 05:18 UTC
![image](https://user-images.githubusercontent.com/3857155/55052132-61524000-508a-11e9-8e4d-fb1d1321a083.png)

**Comment by jpmonettas** [comment] 2019-03-27 22:31
@madvas I couldn't reproduce this in Chrome Linux, works fine. @danielglauser maybe you can try in mac?

**Comment by jpmonettas** [comment] 2019-03-27 22:54
It was a react key issue, only happened when going thru the process. Anyway should be fixed

**Closed** 2019-03-27 23:34 UTC
Labels: MVP
