### ISSUE TITLE
[QA] Cancel button is greyed out on 'Submit' page

### ISSUE THREAD

**Issue by Bradymck** [district0x/memefactory#137] opened 2019-03-04 22:06 UTC
The submit button always remains greyed out.

 ![submit](https://user-images.githubusercontent.com/4667076/53766054-06646900-3e8f-11e9-96f2-651eab29183a.PNG)

**Comment by madvas** [comment] 2019-03-05 05:34
That's how cancel button is, it's not grayed out, it's clickable. That's how we got it from designers, can be changed though.

**Comment by Bradymck** [comment] 2019-03-05 14:17
Okay. Not a problem. Just pointing it out. Many of these issues can be closed out at your discretion. Most are minor design decisions

**Comment by jpmonettas** [comment] 2019-03-07 14:14
Closing since is expected behavior

**Closed by jpmonettas** 2019-03-07 14:14 UTC
